version: 2

sources:
  - name: dhsaphana_stg
    schema: dhsaphana_stg
  
  - name: dhsaphana_sapabap1
    schema: dhsaphana_saphanadb
    tables:
      - name: dd07l
      - name: dd07t
      - name: ekbe
      - name: eket
      - name: ekko
      - name: ekpo
      - name: kna1
      - name: lfa1
      - name: makt
      - name: mara
      - name: t001
      - name: t001w
      - name: t024
      - name: t024e
      - name: t134
      - name: t134t
      - name: t161
      - name: t161t
      - name: tvag
      - name: tvagt
      - name: vbak
      - name: vbap
      - name: vbuk
      - name: vbup
