Select
VBAP.MANDT as Client_Id
,VBAP.POSNR as Sales_Document_Item_Id
,VBAP.VBELN as Sales_Document_Id
,VBAP.SMENG as Scale_Quantity
,VBAP.STLTY as Bom_Category
,VBAP.VGREF as Preceding_Document_Resulted_From_Ref
,VBAP.BWTAR as Valuation_Type_Id
,VBAP.KNUMA_AG as Sales_Deal_Id
,VBAP.SPART as Division_Id
,VBAP.BWTEX as Indicator_Separate_Valuation
,VBAP.OIH_LICIN as Internal_License_No_Id
,VBAP.OIC_DCOUNC as Destination_County_Code_Id
,VBAP.KNUMA_PI as Promotion_Id
,VBAP.OIC_DCITYC as Destination_City_Code_Id
,VBAP.TAS as Treasury_Account_Symbol
,VBAP.OIGNRULE as Gross_Net_Pricing_Rule_Id
,VBAP.UPMAT as Mnitm_Prcrefmatl_Id
,VBAP.KALSM_K as Costing_Sheet_Id
,VBAP.OICERTF1_EX as External_License_No
,VBAP.APLZL_OLC as Counter
,VBAP.UMVKN as Denominator
,VBAP.OIDMSG_QTY as Quantity_Message
,VBAP.KEVER as Deviation_Days
,VBAP.MTVFP as Availability_Check_Id
,VBAP.OIHANTYP_EX as Handling_Type_Id
,VBAP.ABGRU as Reason_Rejection_Id
,VBAP.XCHAR as Batch_Management
,VBAP.KOSTL as Cost_Center_Id
,VBAP._ACCGO_TX_P as _Accgo_Tx_P
,VBAP.PRS_WORK_PERIOD as Work_Period
,VBAP.VKGRU as Repair_Classification_Items_Id
,VBAP.WKTNR as Value_Contract_No_Id
,VBAP.ABSFZ as Absolute_Deviation
,VBAP.OIH_LCFOL as Follow_On_License_Id
,VBAP.VBEAF as Fixed_Process_Time
,VBAP.ERNAM as Created_By
,VBAP.OITAXFROM_IM as Tax_Key_From_Id
,VBAP.STAFO as Update_Group_Stats_Id
,VBAP.OIC_LIFNR as Vendor_Id
,VBAP.J_1BTXSDC as Sd_Tax_Code_Id
,VBAP.TAXM1 as Tax_Classification_Id
,VBAP.LPRIO as Delivery_Priority_Id
,VBAP.OIEDBALM_EX as Balance_Method_Ind
,VBAP.UMZIZ as Conversion_Factor
,VBAP.KZVBR as Consumption_Posting
,VBAP.OIC_AORGIN as Alternate_Origin
,VBAP._SLCE_INST_GUID as _Slce_Inst_Guid
,VBAP.CHARG as Batch_Id
,VBAP.STLKN as Bom_Item_Node_Number
,VBAP.FSH_COLLECTION as Fashion_Collection_Id
,VBAP.CMETH as Quantity_Conversion_Method
,VBAP.APLZL_OAA as APLZL_OAA
,VBAP.OIDMSG_DAT as Validity_Date_Msg
,VBAP.UMVKZ as Numerator
,VBAP.OITAXGRP_EX as Excise_Duty_Group_Id
,VBAP.FSH_CANDATE as Cancellation_Date
,VBAP.OIPRICIE_IM as Ed_Pricing_External
,VBAP._SLCE_SOL_POSNR as _Slce_Sol_Posnr
,VBAP.TAX_SUBJECT_ST as Tax_Subject_To_Substituicao_Tributaria
,VBAP.GEWEI as Weight_Uom_Id
,VBAP.REVACC_REFID as Revenue_Accounting_Reference_Id
,VBAP.OIC_PORGIN as Tax_Origin
,VBAP.SOBKZ as Special_Stock_Id
,VBAP.VPWRK as Planning_Plant_Id
,VBAP.WAERK as Sd_Document_Currency_Id
,VBAP.MOD_ALLOW as Modification_Allowed
,VBAP.UMZIN as UMZIN
,VBAP.MAGRV as Matl_Grp_Pack_Matls_Id
,VBAP.OIC_PBATCH as Pipe_Ex_Batch_No
,VBAP.BONUS as Volume_Rebate_Group_Id
,VBAP.SLOCTYPE as Location_Type
,VBAP.OIEDBAL_IM as Ed_Balance_Indicator
,VBAP.FSH_VAS_PRNT_ID as Sd_Item_Id
,VBAP.ABLFZ as Rounding_Quantity_Delivery
,VBAP.TAXM3 as TAXM3
,VBAP.PSTYV as Sales_Document_Item_Category_Id
,VBAP._XLSO_COURSE_EDA as _Xlso_Course_Eda
,VBAP.FISCAL_INCENTIVE as Tax_Incentive_Type_Id
,VBAP.OIC_MOT as Mode_Transport_Id
,VBAP.OIC_OREGIO as Origin_Region_Id
,VBAP.FISTL as Funds_Center_Id
,VBAP.VPMAT as Planning_Material_Id
,VBAP.AWAHR as Order_Probability_The_Item
,VBAP.KPEIN as Condition_Pricing_Unit
,VBAP.VOLEH as Volume_Uom_Id
,VBAP.WERKS as Plant_Own_Or_External_Id
,VBAP.OICERTF1 as OICERTF1
,VBAP.KNUMH as No_Cond_Rec_Batch
,VBAP.TAXM2 as TAXM2
,VBAP.FSH_PSM_PFM_SPLIT as Psm_And_Pfm_Split_Id
,VBAP.TC_AUT_DET as Tax_Code_Automatically_Determined_Id
,VBAP.SERAIL as Serial_Number_Profile_Id
,VBAP.KOSCH as Product_Allocation_Id
,VBAP.OID_MISCDL as Miscellaneous_Delivery_Number
,VBAP.OIH_LICTP_EX as License_Type_Id
,VBAP.PAOBJNR as Profitability_Segment_No
,VBAP.PS_PSP_PNR as Wbs_Element_Id
,VBAP.RKFKF as Billing_Meth_Co_Ppc
,VBAP.SKTOF as Cash_Discount_Indicator
,VBAP.FKREL as Relevant_Billing
,VBAP.OIHANTYP as OIHANTYP
,VBAP._SLCE_SOL_MATNR as _Slce_Sol_Matnr
,VBAP.OIPLANTD as Is_Oil_Plant_Determ
,VBAP.LSTANR as Free_Goods_Delivery_Control
,VBAP._DATAAGING as Filter_Value_Aging_Date
,VBAP.CPD_UPDAT as Time_Stamp
,VBAP.OIC_DRCREG as Drc_Region_Id
,VBAP.BEDAE as Requirements_Type_Id
,VBAP.MANUAL_TC_REASON as Manual_Tax_Code_Reason_Id
,VBAP.SPCSTO as Nf_Cfop_Special_Case_Id
,VBAP.AEDAT as Changed_Date
,VBAP.Z_PRS_OFFSHORE as On_Near_Offshore_Delivery_Type
,VBAP.KZWI1 as Subtotal_1_Val
,VBAP.OIEDOK as Excise_Duty_Validation_Indicator
,VBAP.FSH_PQR_UEPOS as Higher_Lev_Item_Partial_Quantity_Rej_Id
,VBAP.HANDOVERTIME as Handover_Tim
,VBAP.XCHPF as XCHPF
,VBAP.OIBWTAR_IM as OIBWTAR_IM
,VBAP.SHKZG as Returns_Item
,VBAP._SLCE_SOL_CUOBJ as _Slce_Sol_Cuobj
,VBAP.AUFPL_OLC as Operation_Task_List_No
,VBAP.NTGEW as Net_Weight_The_Item
,VBAP.VGTYP as Preceding_Doc_Categ
,VBAP.STOCKLOC as Location
,VBAP.PMATN as Pricing_Reference_Material_Id
,VBAP.SERNR as Bom_Explosion_Number_Id
,VBAP.TAXM4 as TAXM4
,VBAP.KALNR as Cost_Estimate_Number_Id
,VBAP.OIEXGNUM as Exchange_Agreement_Number_Id
,VBAP.ERLRE as Completion_Rule
,VBAP.OIEXGTYP as Exchange_Type_Id
,VBAP.OITAXTO_IM as Tax_Key_To_Id
,VBAP.KZBWS as Special_Stock_Valuation
,VBAP._ACCGO_IS_CO_REL as _Accgo_Is_Co_Rel
,VBAP.PARGB as Trading_Partba_Id
,VBAP.OIMETIND as Metropolitan_Indicator_Id
,VBAP.OIH_FOLQTY as 2Nd_License_Qty
,VBAP.OIC_TRUCKN as Truck_Number
,VBAP.UEBTK as Unlimited_Overdelivery_Allowed
,VBAP.ARSNUM as Reservation_Id
,VBAP.KDMAT as Material_Number_Used_By_Customer
,VBAP.BPN as Business_Partner_Number_Id
,VBAP.MVGR1 as Material_Group_1_Id
,VBAP.VOREF as Complete_Reference_Indicator
,VBAP.ERZET as Created_Tim
,VBAP.ARKTX as Short_Text_Sales_Order_Item
,VBAP.CMPNT as Credit_Funct_Active
,VBAP.OIHNOTLGORT as Storage_Loc_Id
,VBAP.UEPOS as Higher_Level_Item_Id
,VBAP.STDAT as Key_The_Bill_Material_Date
,VBAP.STCUR as Exchange_Rate_Stats
,VBAP.OITAXFROM_EX as OITAXFROM_EX
,VBAP.FISCAL_INCENTIVE_ID as Incentive_Id
,VBAP._SLCE_SINGLE_CONF_DONE as _Slce_Single_Conf_Done
,VBAP.KLMENG as Cumul_Confirmed_Qty
,VBAP.ZMENG as Target_Quantity_In_Sales_Units
,VBAP.OIDRC as Differ_Refer_Code_Id
,VBAP.PAY_METHOD as Payment_Methods
,VBAP._SLCE_SOL_EXT_GUID as _Slce_Sol_Ext_Guid
,VBAP.KZWI2 as Subtotal_2_Val
,VBAP.OIBYPASS as Is_Oil_Plt_Det_Ind
,VBAP.FSH_ITEM_GROUP as Item_Group
,VBAP.AUFPL_OAA as AUFPL_OAA
,VBAP.KWMENG as Order_Quantity
,VBAP.OIH_LCFOL_EX as OIH_LCFOL_EX
,VBAP.KOUPD as Condition_Update
,VBAP.FSH_GRID_COND_REC as Grid_Condition_Number
,VBAP.TECHS as Standard_Variant
,VBAP.MATNR as Material_Id
,VBAP.WGRU1 as Material_Group_Hierarchy_1
,VBAP.OITAXFROM as OITAXFROM
,VBAP.TAXM5 as TAXM5
,VBAP.KZTLF as Partial_Delivery_At_Item_Level
,VBAP.IUID_RELEVANT as Iuid_Relevant_Customer
,VBAP.OIC_KMPOS as Ref_Contract_Item
,VBAP.Z_PRS_COUNTRY as Country_Key_Id
,VBAP.GSBER as Business_Area_Id
,VBAP.OIPRICIE_EX as OIPRICIE_EX
,VBAP.FSH_CRSD as Condition_No
,VBAP.FSH_TRANSACTION as Transaction_Number
,VBAP.GRKOR as Delivery_Group
,VBAP.UEPVW as Id_Higher_Level_Item_Usage
,VBAP.MFRGR as Material_Freight_Group_Id
,VBAP.VBELV as Originating_Document_Id
,VBAP.UNTTO as Underdelivery_Tolerance_Limit
,VBAP.PLAVO as Plandelschedinstruct_Id
,VBAP.VPZUO as Allocation_Indicator
,VBAP.MVGR3 as Material_Group_3_Id
,VBAP.SUGRD as Reason_Material_Substitution_Id
,VBAP.OIC_PTRIP as Pipeline_Trip_Number_External
,VBAP.OIC_ADESTN as Alternate_Destination
,VBAP.OIC_OLAND1 as Origin_Country_Id
,VBAP.MVGR2 as Material_Group_2_Id
,VBAP.NETPR as Net_Price_Val
,VBAP.OICONTNR as Outline_Agreement_Contract_Id
,VBAP.STMAN as Inconsistent_Configuration
,VBAP.OIEDBAL_EX as OIEDBAL_EX
,VBAP.J_1BTAXLW3 as Iss_Tax_Law_Id
,VBAP._SLCE_SINGLE_CONF_REQIRED as _Slce_Single_Conf_Reqired
,VBAP.OINETCYC as Netting_Cycle_Id
,VBAP.PRSOK as Pricing_Is_Ok
,VBAP.VGPOS as Reference_Item_Id
,VBAP.CUOBJ_CH as Internal_Object_No
,VBAP.OIC_PDESTN as Tax_Destination
,VBAP.REP_FREQ as Reporting_Frequency
,VBAP.LSMENG as Required_Deliv_Qty
,VBAP.STPOZ as STPOZ
,VBAP.KZWI3 as Subtotal_3_Val
,VBAP.POSAR as Item_Type
,VBAP.BUDGET_PD as Budget_Period_Id
,VBAP.Z_PRS_CHARGELEVL as Staff_Grade
,VBAP.POSNV as Originating_Item_Id
,VBAP.WGRU2 as Material_Group_Hierarchy_2
,VBAP.OIFEETOT as Fee_Total_Val
,VBAP.OIC_DREGIO as Destination_Region_Id
,VBAP.OIH_LICIN_EX as OIH_LICIN_EX
,VBAP.OIOILCON as Oil_Content_Perc
,VBAP.AUFNR as Order_Id
,VBAP.SGT_RCAT as Requirement_Segment
,VBAP.OIDMSG_UOM as Unit_Measure_Msg
,VBAP.OIBASPROD as Base_Product_Number_Id
,VBAP.MSR_REFUND_CODE as Returns_Refund_Code_Id
,VBAP.CUOBJ as Configuration
,VBAP.KBVER as Deviation_In_Percent
,VBAP.SPOSN as Bom_Item_Number
,VBAP.FSH_SEASON_YEAR as Season_Year_Id
,VBAP.ZZDEA_LICENSE as Dea_Number
,VBAP.TAXM6 as TAXM6
,VBAP.MPROK as Status_Manual_Price_Change
,VBAP.PROVG as Commission_Group_Id
,VBAP.OITAXTO as OITAXTO
,VBAP.CMKUA as Cred_Exch_Rate
,VBAP.CMTFG as Partial_Release
,VBAP.OID_EXTBOL as External_Bill_Lading
,VBAP.UKONM as Mnitem_Matpricinggrp_Id
,VBAP.MVGR4 as Material_Group_4_Id
,VBAP.KMEIN as Condition_Uom_Id
,VBAP.KLVAR as Costing_Variant_Id
,VBAP.PRS_SD_SPSNR as Standard_Wbs_Element_Id
,VBAP.MWSBP as Tax_Amount_Document_Currency_Val
,VBAP.REVACC_REFTYPE as Rev_Acc_Reference_Type
,VBAP.WRF_CHARSTC1 as Characteristic_Value_1
,VBAP.FSH_ITEM as Item_Number
,VBAP.SKOPF as Assortment_Module_Id
,VBAP.OIBWTAR_EX as OIBWTAR_EX
,VBAP.PRODH as Product_Hierarchy_Id
,VBAP.STKEY as Origin_The_Bill_Material
,VBAP.J_1BTAXLW4 as Cofins_Tax_Law_Id
,VBAP.ROUTE as Route_Id
,VBAP._XLSO_COURSE_BDA as _Xlso_Course_Bda
,VBAP.MATKL as Material_Group_Id
,VBAP.OIC_DRCTRY as Drc_Country_Id
,VBAP.KALVAR as KALVAR
,VBAP.LFREL as Item_Is_Relevant_Delivery
,VBAP.KMPMG as Component_Quantity
,VBAP.KZWI4 as Subtotal_4_Val
,VBAP.WTYSC_CLMITEM as Claim_Item_Number
,VBAP.FMENG as Quantity_Is_Fixed
,VBAP.NRAB_KNUMH as Condition_Number
,VBAP.OITAXTO_EX as OITAXTO_EX
,VBAP.CMPRE as Item_Credit_Price_Val
,VBAP.HANDOVERDATE as Handover_Date
,VBAP.NACHL as No_Gr_Posted_By_Cst
,VBAP.ABDAT as Reconciliation_Date
,VBAP.KONDM as Material_Pricing_Group_Id
,VBAP.OIC_DLAND1 as Destination_Country_Id
,VBAP.CMPRE_FLT as Item_Credit_Price
,VBAP.TAXM7 as TAXM7
,VBAP.FERC_IND as Regulatory_Indicator_Id
,VBAP.OIFEECH as Fee_Edit_Control
,VBAP.OIH_FOLQTY_EX as OIH_FOLQTY_EX
,VBAP.PRCTR as Profit_Center_Id
,VBAP.EANNR as Ean_Number
,VBAP.ZSCHL_K as Overhead_Key
,VBAP.OISLF as State_License_Fee_Zone_Id
,VBAP.PCTRF as Profit_Center_Billing_Id
,VBAP.FSH_VAS_REL as Vas_Relevant
,VBAP.MVGR5 as Material_Group_5_Id
,VBAP.FKBER as Functional_Area_Id
,VBAP.VBEAV as Var_Processing_Time
,VBAP.ZWERT as Oa_Target_Val
,VBAP.ANTLF as Max_Part_Deliveries
,VBAP.CANCEL_ALLOW as Cancellation_Allowed
,VBAP.FSH_SEAREF as Copied_Season
,VBAP.OIPRICIE as OIPRICIE
,VBAP.WRF_CHARSTC2 as Characteristic_Value_2
,VBAP.UPFLU as Update_Document_Flow
,VBAP.OIHCOTDISCH as Imp_Posting_At_Pod
,VBAP.OIDMSG_SHP as Ship_To_Party_Msg
,VBAP.GRANT_NBR as Grant
,VBAP.OIDMSG_TRM as Payment_Terms_Msg
,VBAP.UMREF as Conversion_Factor_Quantities
,VBAP.KZWI6 as Subtotal_6_Val
,VBAP.KNTTP as Account_Assignment_Category_Id
,VBAP.J_1BTAXLW5 as Pis_Tax_Law_Id
,VBAP.STLNR as Bill_Material
,VBAP.VKAUS as Usage_Id
,VBAP.ERDAT as Created_Date
,VBAP.KZWI5 as Subtotal_5_Val
,VBAP.FSH_THEME as Fashion_Theme_Id
,VBAP.FSH_SEASON as Season_Id
,VBAP.ZIEME as Target_Quantity_Uom_Uom_Id
,VBAP.OIPSDRC as Pricing_Drc_Id
,VBAP.UEBTO as Overdelivery_Tolerance_Limit
,VBAP.GRPOS as Alternative_To_Item
,VBAP.CHMVS as Quantity_Proposal
,VBAP.OIHANTYP_IM as OIHANTYP_IM
,VBAP.ABGES as Guaranteed
,VBAP.OIHNOTWERKS as Cross_Excise_Duty_Plant_Id
,VBAP.Z_PRS_BILL_FLAG as Billable_Non_Billable
,VBAP.ABGRS as Results_Analysis_Key_Id
,VBAP.TAXM8 as TAXM8
,VBAP.OBJNR as Object_Number_At_Item_Level_Id
,VBAP.VOLUM as Volume_The_Item
,VBAP.OIINEX_EX as Ed_Pricing_Key_Id
,VBAP.J_1BTAXLW1 as Icms_Law_Id
,VBAP.J_1BCFOP as Cfop_Code_And_Extension_Id
,VBAP.KOWRR as Statistical_Values
,VBAP.FIXMG as Delivery_Date_And_Quantity_Fixed
,VBAP._XLSO_COURSE_ID as _Xlso_Course_Id
,VBAP.FMFGUS_KEY as Us_Government_Fields
,VBAP.ATPKZ as Replacement_Part
,VBAP.OIFEEDT as Fee_Pricing_Condition_Date
,VBAP.MEINS as Base_Uom_Id
,VBAP.OIINEX as OIINEX
,VBAP.MSR_RET_REASON as Return_Reason_Id
,VBAP.HANDOVERLOC as Handover_Location
,VBAP.LFMNG as Minimum_Delivery_Qty
,VBAP.KTGRM as Acct_Assignment_Grp_Id
,VBAP.OIA_BASELO as Base_Location
,VBAP.BETC as Business_Event_Type_Code
,VBAP.WRF_CHARSTC3 as Characteristic_Value_3
,VBAP.OIEDBALM_IM as OIEDBALM_IM
,VBAP.OIHTAXRCP_EX as Tax_Recipient
,VBAP.OIC_OCOUNC as Origin_County_Code_Id
,VBAP.EXART as Bus_Transaction_Type_Id
,VBAP.FSH_VASREF as Copied_Vas
,VBAP.OIWAP as Wide_Area_Pricing_Zone_Id
,VBAP.VGBEL as Reference_Document_Id
,VBAP.KANNR as Kanban_Sequence_Number
,VBAP.SUMBD as Summing_Up_Requirements
,VBAP.OIDMSG_PRD as Products_Message
,VBAP.POSEX as Purchase_Order_Item
,VBAP.OITAXGRP_IM as OITAXGRP_IM
,VBAP.OIC_OCITYC as Origin_City_Code_Id
,VBAP.OID_SHIP as Ship_To_Party_Id
,VBAP.PROSA as Id_Material_Determination
,VBAP.BERID as Mrp_Area_Id
,VBAP.LOGSYS_EXT as Logical_System_Id
,VBAP.OIPIPEVAL as Val_Ind_Pipeline
,VBAP.OITAXGRP as OITAXGRP
,VBAP.VRKME as Sales_Uom_Id
,VBAP.EAN11 as Ean
,VBAP.TAXM9 as TAXM9
,VBAP.KZFME as Leading_Uom
,VBAP.WKTPS as Value_Contract_Item_Id
,VBAP.J_1BTAXLW2 as Ipi_Law_Id
,VBAP.OIEDBALM as OIEDBALM
,VBAP.STPOS as Bill_Material_Item_Number
,VBAP.ANZSN as Number_Serial_Numbers
,VBAP.OISBREL as S_B_Prod_Relev_Ind
,VBAP.OIH_LICTP as OIH_LICTP
,VBAP.WAVWR as Cost_Document_Currency_Val
,VBAP.ARSPOS as Item_No_Reservation
,VBAP._BEV1_SRFUND as _Bev1_Srfund
,VBAP.NETWR as Net_Val
,VBAP.PRS_OBJNR as Engagement_Mgmt_Object_Number
,VBAP.KBMENG as KBMENG
,VBAP.PREFE as Preference_Auth
,VBAP.PRBME as Product_Group_Uom_Id
,VBAP.CLINT as Internal_Class_Number_Id
,VBAP.ZZDEA_SCHEDULE as Dea_Schedule_Key
,VBAP.OIEDBAL as OIEDBAL
,VBAP.TRMRISK_RELEVANT as Risk_Relevancy_In_Sales
,VBAP.CHSPL as Batch_Split_Allowed
,VBAP.MATWA as Material_Entered_Id
,VBAP.FAKSP as Billing_Block_Item_Id
,VBAP.FONDS as Fund_Id
,VBAP.BRGEW as Gross_Weight_The_Item
,VBAP.ABFOR as Form_Payment_Guarantee_Id
,VBAP.STADAT as Statistics_Date
,VBAP.VSTEL as Shipping_Point_Id
,VBAP.MILL_SE_GPOSN as Global_Item_Id
,VBAP.LGORT as Storage_Location_Id
,VBAP.MSR_APPROV_BLOCK as Approval_Block
,VBAP.CEPOK as Status_Expected_Price
,VBAP._FIVETRAN_DELETED as _Fivetran_Deleted
,VBAP._FIVETRAN_SYNCED as _Fivetran_Synced
,VBAP._FIVETRAN_SAP_ARCHIVED as _Fivetran_Sap_Archived
from {{source('dhsaphana_sapabap1', 'vbap')}}
where
VBAP.MANDT in ('800')